services:
  flask:
    build: ./flask
    volumes:
      - ./flask:/usr/src/app
    expose:
      - "5000"

  nginx:
    build: ./nginx
    ports:
      - "7081:80"
    depends_on:
      - flask

  redis:
    build: ./redis
    volumes:
      - redis-data:/data

volumes:
  redis-data:
